#!/bin/bash
# SANDBOX_DIR should refer to the directory in which sandbox is placed.
#SANDBOX_DIR=~/sandbox
#SANDBOX_DIR=/usr/local/sandbox
SANDBOX_DIR=.

SANDBOX_OPTIONS="-r"
#SANDBOX_OPTIONS="-r -q${HOME}/.platinumarts"

if [ -a ${SANDBOX_DIR}/bin_unix/native_client ]
then
	cd ${SANDBOX_DIR}
	chmod +x bin_unix/native_*
	exec ./bin_unix/native_client $SANDBOX_OPTIONS $*
else
	echo "A problem was encountered, please check which of the following it is."
	echo "1) the executable was moved"
	echo "2) There isn't an executable"
	echo "the script will attempt to create a client in 10 seconds, press CTRL-C to cancel"
	sleep 10
	cd src
	chmod +x build.sh
	exec build.sh
	cd ../
	exit 1
fi
